version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  udagram-api-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
  udagram-api-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
  udagram-frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:latest