apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-secret.yml
  - env-configmap.yml
  - env-secret.yml
  - api-feed-deployment.yml
  - api-feed-service.yml
  - api-user-deployment.yml
  - api-user-service.yml
  - reverseproxy-deployment.yml
  - reverseproxy-service.yml
  - frontend-deployment.yml
  - frontend-service.yml
namespace: default
