# Workflow name
name: Reverse Proxy

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch: null
  
  # Automatic trigger on push events to the main branch
  push:
    branches:
      - main
    paths:
      - "udagram-frontend/**"
      
  # Automatic trigger on pull request events targeting the main branch
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - "udagram-reverseproxy/**"
      
  # Scheduled trigger at 5:00 AM UTC, Monday through Friday
  # schedule:
  #   - cron: '0 5 * * 1-5'

# Jobs defined in the workflow
jobs:
  build-docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker images
        env:
          REGISTRY: thanhpt0105
          REPOSITORY: udagram-frontend
          IMAGE_TAG: latest
        run: |
          cd udagram-frontend
          docker build -t udagram-frontend .
          docker tag udagram-frontend $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  # post-build-actions:
  #   needs: [build-and-test-1, build-and-test-2]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Publish test results
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: test-results
  #         path: test-results.xml